{
    "artifact_type": "RESOURCE",
    "typeName": "TF::CheckPoint::ManagementExceptionGroup",
    "language": "python37",
    "runtime": "python3.7",
    "entrypoint": "tf_checkpoint_managementexceptiongroup.handlers.resource",
    "testEntrypoint": "tf_checkpoint_managementexceptiongroup.handlers.test_entrypoint",
    "settings": {
        "version": false,
        "subparser_name": "python37",
        "verbose": 0,
        "force": false,
        "type_name": "TF::CheckPoint::ManagementExceptionGroup",
        "artifact_type": "RESOURCE",
        "use_docker": true,
        "language": "python37",
        "protocolVersion": "2.0.0"
    }
}
